# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  application:
    name: Product
    debug: enabled
  datasource:
    url: "jdbc:postgresql://localhost:5432/product"
    username: "knits"
    password: "ad1b0l4ad3b0l4$t3"

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: false

  mvc:
    format:
      date-time: iso


server:
  port: 8081

debug: false

logging:
  level:
    liquibase: INFO